export const data = [
  {
    id: 1,
    first_name: "Cherie",
    last_name: "Hair",
    area:"pune",
    category:"grocery",
    image: "http://dummyimage.com/100x100.png/ff4444/ffffff",
    avatar: "https://robohash.org/inutofficia.png?size=150x150&set=set1",
  },
  {
    id: 2,
    first_name: "Catharina",
    last_name: "Bierman",
    area:"pune",
    category:"grocery",
    image: "http://dummyimage.com/100x100.png/ff4444/ffffff",
    avatar: "https://robohash.org/quiaatcommodi.png?size=150x150&set=set1",
  },
  {
    id: 3,
    first_name: "Vernen",
    last_name: "Dummigan",
    area:"pune",
    category:"grocery",
    image: "http://dummyimage.com/100x100.png/cc0000/ffffff",
    avatar: "https://robohash.org/voluptasquisaut.png?size=150x150&set=set1",
  },
  {
    id: 4,
    first_name: "Coralie",
    last_name: "Domenge",
    email: "cdomenge3@eepurl.com",
    gender: "Male",
    ip_address: "195.92.89.100",
    date: "2020-12-29T18:12:32Z",
    image: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
    avatar: "https://robohash.org/deseruntcumipsam.png?size=150x150&set=set1",
  },
  {
    id: 5,
    first_name: "Willamina",
    last_name: "Kinson",
    area:"pune",
    category:"grocery",
    image: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
    avatar:
      "https://robohash.org/repudiandaeauteaque.png?size=150x150&set=set1",
  },
  {
    id: 6,
    first_name: "Tildie",
    last_name: "Rochester",
    area:"pune",
    category:"grocery",
    image: "http://dummyimage.com/100x100.png/ff4444/ffffff",
    avatar:
      "https://robohash.org/ipsamessevoluptatibus.png?size=150x150&set=set1",
  },
  {
    id: 7,
    first_name: "Rudolph",
    last_name: "Amiss",
    email: "ramiss6@feedburner.com",
    gender: "Non-binary",
    ip_address: "169.156.6.200",
    date: "2021-05-01T21:29:40Z",
    image: "http://dummyimage.com/100x100.png/ff4444/ffffff",
    avatar: "https://robohash.org/idauterror.png?size=150x150&set=set1",
  },
  {
    id: 8,
    first_name: "Marie-jeanne",
    last_name: "Singyard",
    area:"pune",
    category:"grocery",
    image: "http://dummyimage.com/100x100.png/dddddd/000000",
    avatar: "https://robohash.org/quoestvel.png?size=150x150&set=set1",
  },
  {
    id: 9,
    first_name: "Jesus",
    last_name: "Castles",
    area:"pune",
    category:"grocery",
    image: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
    avatar: "https://robohash.org/sitmolestiaequasi.png?size=150x150&set=set1",
  },
  {
    id: 10,
    first_name: "Harley",
    last_name: "Hightown",
    area:"pune",
    category:"grocery",
    image: "http://dummyimage.com/100x100.png/dddddd/000000",
    avatar: "https://robohash.org/quieaquesimilique.png?size=150x150&set=set1",
  },
  {
    id: 11,
    first_name: "Georgette",
    last_name: "Borzone",
    area:"solapur",
    category:"Statinary",
    image: "http://dummyimage.com/100x100.png/dddddd/000000",
    avatar:
      "https://robohash.org/nihiliustovoluptatem.png?size=150x150&set=set1",
  },
  {
    id: 12,
    first_name: "Lianna",
    last_name: "Dunbobbin",
    area:"solapur",
    category:"Statinary",
    image: "http://dummyimage.com/100x100.png/cc0000/ffffff",
    avatar:
      "https://robohash.org/aliasconsequaturfugit.png?size=150x150&set=set1",
  },
  {
    id: 13,
    first_name: "Tabitha",
    last_name: "Dany",
    area:"solapur",
    category:"Statinary",
    image: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
    avatar:
      "https://robohash.org/odiodeseruntvoluptatem.png?size=150x150&set=set1",
  },
  {
    id: 14,
    first_name: "Jehanna",
    last_name: "Vallerine",
    area:"solapur",
    category:"Statinary",
    image: "http://dummyimage.com/100x100.png/ff4444/ffffff",
    avatar: "https://robohash.org/hicauteos.png?size=150x150&set=set1",
  },
  {
    id: 15,
    first_name: "Jerrylee",
    last_name: "Skakunas",
    area:"solapur",
    category:"Statinary",
    image: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
    avatar:
      "https://robohash.org/blanditiisvoluptatemfugit.png?size=150x150&set=set1",
  },
  {
    id: 16,
    first_name: "Artus",
    last_name: "Majury",
    area:"Nagpur",
    category:"Statinary",
    image: "http://dummyimage.com/100x100.png/dddddd/000000",
    avatar: "https://robohash.org/veroetculpa.png?size=150x150&set=set1",
  },
  {
    id: 17,
    first_name: "Roxine",
    last_name: "Boughtflower",
    area:"Nagpur",
    category:"Statinary",
    image: "http://dummyimage.com/100x100.png/ff4444/ffffff",
    avatar: "https://robohash.org/repellendusautemet.png?size=150x150&set=set1",
  },
  {
    id: 18,
    first_name: "Guglielmo",
    last_name: "Berthelmot",
    area:"Nagpur",
    category:"Statinary",
    image: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
    avatar: "https://robohash.org/magniutdolor.png?size=150x150&set=set1",
  },
  {
    id: 19,
    first_name: "Tybi",
    last_name: "Pollett",
    area:"mumbai",
    category:"baker",
    image: "http://dummyimage.com/100x100.png/ff4444/ffffff",
    avatar:
      "https://robohash.org/remvoluptatemofficiis.png?size=150x150&set=set1",
  },
  {
    id: 20,
    first_name: "Valentin",
    last_name: "Ferryman",
    area:"mumbai",
    category:"baker",
    image: "http://dummyimage.com/100x100.png/cc0000/ffffff",
    avatar: "https://robohash.org/utquibusdamet.png?size=150x150&set=set1",
  },
  {
    id: 21,
    first_name: "Jeanelle",
    last_name: "Corsar",
    area:"mumbai",
    category:"baker",
    image: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
    avatar:
      "https://robohash.org/autemvoluptasaspernatur.png?size=150x150&set=set1",
  },
  {
    id: 22,
    first_name: "Casi",
    last_name: "Lammie",
    area:"mumbai",
    category:"baker",
    image: "http://dummyimage.com/100x100.png/ff4444/ffffff",
    avatar:
      "https://robohash.org/doloremquecorporisharum.png?size=150x150&set=set1",
  },
  {
    id: 23,
    first_name: "Cyrill",
    last_name: "Castagno",
    area:"ahmednager",
    category:"Chemist",
    image: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
    avatar: "https://robohash.org/doloremnullarerum.png?size=150x150&set=set1",
  },
  {
    id: 24,
    first_name: "Ardath",
    last_name: "Renvoise",
    area:"ahmednager",
    category:"Chemist",
    image: "http://dummyimage.com/100x100.png/dddddd/000000",
    avatar: "https://robohash.org/iuresedincidunt.png?size=150x150&set=set1",
  },
  {
    id: 25,
    first_name: "Helsa",
    last_name: "Stopher",
    area:"ahmednager",
    category:"Chemist",
    image: "http://dummyimage.com/100x100.png/dddddd/000000",
    avatar: "https://robohash.org/quieumearum.png?size=150x150&set=set1",
  },
  {
    id: 26,
    first_name: "Hazel",
    last_name: "Letford",
    area:"ahmednager",
    category:"Chemist",
    image: "http://dummyimage.com/100x100.png/cc0000/ffffff",
    avatar:
      "https://robohash.org/consequunturautquod.png?size=150x150&set=set1",
  },
  {
    id: 27,
    first_name: "Brittani",
    last_name: "Castagno",
    area:"ahmednager",
    category:"Chemist",
    image: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
    avatar:
      "https://robohash.org/explicaboliberooptio.png?size=150x150&set=set1",
  },
  {
    id: 28,
    first_name: "Mady",
    last_name: "Pigott",
    email: "mpigottr@si.edu",
    gender: "Genderqueer",
    ip_address: "66.117.125.143",
    date: "2021-04-05T11:59:44Z",
    image: "http://dummyimage.com/100x100.png/ff4444/ffffff",
    avatar: "https://robohash.org/eligendivelitodit.png?size=150x150&set=set1",
  },
  {
    id: 29,
    first_name: "Biron",
    last_name: "Heeks",
    area:"ahmednager",
    category:"Chemist",
    date: "2021-06-16T12:50:53Z",
    image: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
    avatar: "https://robohash.org/quiasitsunt.png?size=150x150&set=set1",
  },
  {
    id: 30,
    first_name: "Hendrika",
    last_name: "Sharrem",
    area:"ahmednager",
    category:"Chemist",
    image: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
    avatar:
      "https://robohash.org/consecteturtotamatque.png?size=150x150&set=set1",
  },
  
];
